# Generated by Django 3.2.16 on 2022-10-24 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity_available', models.IntegerField(max_length=5, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)])),
                ('Battery', models.FloatField(max_length=7)),
                ('RAM', models.IntegerField(max_length=2, validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(1)])),
                ('Storage', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
