# Generated by Django 3.2.16 on 2022-10-24 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='RAM',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='quantity_available',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
