# Generated by Django 3.2.16 on 2022-10-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Products.phone'),
        ),
    ]
